INSERT INTO creatures (name, species, danger_level, condition, notes, habitat_id, created_at)
VALUES
    ('Nyx', 'Void Fox', 'HIGH', 'CAUTIOUS', 'Avoid bright light', 1, NOW()),
    ('Emberclaw', 'Fire Raptor', 'HIGH', 'STABLE', 'Extremely territorial', 5, NOW()),
    ('Glint', 'Crystal Beetle', 'LOW', 'STABLE', 'Feeds on minerals', 1, NOW()),
    ('Mireling', 'Swamp Wisp', 'MEDIUM', 'CRITICAL', 'Do not inhale spores', 5, NOW()),
    ('Frostbite', 'Ice Serpent', 'HIGH', 'STABLE', 'Keep below freezing', 4, NOW()),
    ('Bramble', 'Thorn Stalker', 'MEDIUM', 'STABLE', 'Camouflages in brush', 1, NOW()),
    ('Dune Runner', 'Sand Strider', 'LOW', 'STABLE', 'Very fast', 2, NOW()),
    ('Abyssus', 'Deep Sea Eel', 'HIGH', 'CAUTIOUS', 'Bioluminescent lure', 4, NOW()),
    ('Zephyr', 'Sky Ray', 'LOW', 'STABLE', 'Glides on air currents', 5, NOW()),
    ('Rumbleback', 'Stone Turtle', 'LOW', 'STABLE', 'Very slow', 5, NOW()),
    ('Vex', 'Shadow Lynx', 'HIGH', 'CAUTIOUS', 'Hostile to humans', 1, NOW()),
    ('Bloom', 'Petal Drake', 'LOW', 'STABLE', 'Herbivore', 3, NOW()),
    ('Silt', 'Mud Crawler', 'LOW', 'CRITICAL', 'Regenerates limbs', 1, NOW()),
    ('Cinder', 'Lava Hound', 'HIGH', 'STABLE', 'Heat resistant', 5, NOW()),
    ('Nimbus', 'Cloud Jelly', 'LOW', 'STABLE', 'Floats', 4, NOW()),
    ('Shard', 'Ice Golem', 'HIGH', 'STABLE', 'Very strong', 1, NOW()),
    ('Root', 'Tree Guardian', 'MEDIUM', 'STABLE', 'Protective behavior', 1, NOW()),
    ('Echo', 'Cave Bat Alpha', 'MEDIUM', 'STABLE', 'Sensitive hearing', 2, NOW()),
    ('Tide', 'Wave Serpent', 'HIGH', 'STABLE', 'Aggressive', 3, NOW()),
    ('Spark', 'Volt Imp', 'MEDIUM', 'CAUTIOUS', 'Electric discharge', 3, NOW()),
    ('Flora', 'Vine Sprite', 'LOW', 'STABLE', 'Photosynthetic', 4, NOW()),
    ('Dust', 'Ash Phantom', 'HIGH', 'CAUTIOUS', 'Invisible in smoke', 3, NOW()),
    ('Glacier', 'Snow Bear', 'MEDIUM', 'STABLE', 'Hibernate cycles', 2, NOW()),
    ('Ridge', 'Mountain Ram Beast', 'LOW', 'STABLE', 'Climbs steep terrain', 5, NOW()),
    ('Bog', 'Swamp Titan', 'HIGH', 'CRITICAL', 'Requires containment', 1, NOW());